shops = Shop.create([
  { name: 'モンタボー', address: '東京都港区麻布十番2-3-3',telephone: '03-3455-7296',image: 'モンタボー.jpg' },
  { name: 'ポワンタージュ', address: '東京都港区麻布十番3-3-10',telephone: '03-5445-4707',image: 'ポワンタージュ.jpg' },
  { name: 'テラコーヒー', address: '横浜市神奈川区白楽129番地',telephone: '045-309-8686',image: 'テラコーヒー.jpg' },
  { name: 'スターバックス太宰府店', address: '福岡県太宰府市宰府3-2-43',telephone: '092-919-5690',image: 'スターバックス太宰府店.jpg' },
  { name: 'ベーカリー', address: '東京都港区南麻布１丁目',telephone: '080-1234-5678',image: 'ベーカリー.jpg' }, 
  { name: 'サンモリッツ', address: '東京都港区元麻布3-11-6',telephone: '03-3408-6381',image: 'サンモリッツ.jpg' },
  { name: 'パンの田島', address: '東京都目黒区自由が丘2-11-11',telephone: '03-6421-2015',image: 'パンの田島.jpg' },
  { name: '乃が美', address: '東京都港区麻布十番1-9-7 麻布KFビル１F',telephone: '03-6441-3188',image: '乃が美.jpg'}])

categories = Category.create([
  { name: 'パン' }, 
  { name: '飲み物' }])

foods = Food.create!([
  { name: 'コロッケパン', price: 200,category_id: 1,image:'コロッケパン.jpg' ,shop_id: 1},
  { name: 'サフジュ', price: 180,category_id: 1,image:'サフジュ.jpg' ,shop_id: 1},
  { name: 'じゃがレンソウ', price: 220,category_id: 1,image:'じゃがレンソウ.jpg' ,shop_id: 1},
  { name: 'プチ・フランス', price: 200,category_id: 1,image:'プチ・フランス.jpg' ,shop_id: 1},
  { name: 'みんなの笑顔メロンパン', price: 200,category_id: 1,image:'みんなの笑顔メロンパン.jpg' ,shop_id: 1},
  { name: '匠クリームパン', price: 210,category_id: 1,image:'匠クリームパン.jpg' ,shop_id: 1},
  { name: '小麦のしずく', price: 400,category_id: 1,image:'小麦のしずく.jpg' ,shop_id: 1},
  { name: '明太子フランス', price: 230,category_id: 1,image:'明太子フランス.jpg' ,shop_id: 1},
  { name: '野沢菜おやき', price: 180,category_id: 1,image:'野沢菜おやき.jpg' ,shop_id: 1},
  { name: 'イベリコ豚とマカダミアナッツのリュスティック', price: 260,category_id: 1,image:'powantaju1.jpg' ,shop_id: 2},
  { name: 'ハーブソーセージとキノコのフォカッチャ', price: 240,category_id: 1,image:'powantaju2.jpg' ,shop_id: 2},
  { name: 'パンドロデブ', price: 190,category_id: 1,image:'powantaju3.jpg' ,shop_id: 2},
  { name: 'マスカルポーネチーズデニッシュ', price: 300,category_id: 1,image:'powantaju4.jpg' ,shop_id: 2},
  { name: '栗と小豆の豆乳パンドミー', price: 280,category_id: 1,image:'powantaju5.jpg' ,shop_id: 2},
  { name: '渋皮栗のデニッシュ', price: 220,category_id: 1,image:'powantaju6.jpg' ,shop_id: 2},
  { name: 'フルーツのロデブ', price: 280,category_id: 1,image:'powantaju7.jpg' ,shop_id: 2},
  { name: 'コーヒーパン', price: 300,category_id: 1 ,image:'コーヒーパン.jpg',shop_id: 3},
  { name: 'きのこ&モッツァレラ石窯フィローネ', price: 300,category_id: 1,image:'sbdazai1.jpg' ,shop_id: 4},
  { name: 'ハム&マリボーチーズ石窯フィローネ', price: 340,category_id: 1,image:'sbdazai2.jpg' ,shop_id: 4},
  { name: 'ミートボールフォカッチャ', price: 330,category_id: 1,image:'sbdazai3.jpg' ,shop_id: 4},
  { name: '海老のビスクフォカッチャ', price: 360,category_id: 1,image:'sbdazai4.jpg' ,shop_id: 4},
  { name: 'ハムエッグホットサンド', price: 360,category_id: 1,image:'sbdazai5.jpg' ,shop_id: 4},
  { name: 'サラダラップ', price: 400,category_id: 1,image:'sbdazai6.jpg' ,shop_id: 4},
  { name: 'アメリカンワッフル', price: 250,category_id: 1,image:'sbdazai7.jpg' ,shop_id: 4},
  { name: 'バナナチョコレートマフィン', price: 250,category_id: 1,image:'sbdazai8.jpg' ,shop_id: 4},
  { name: 'フレンチトースト', price: 250,category_id: 1,image:'sbdazai9.jpg' ,shop_id: 4},
  { name: 'クロワッサン', price: 250,category_id: 1,image:'クロワッサン.jpg',shop_id: 5 }, 
  { name: '食パン', price: 400,category_id: 1,image:'食パン.jpg' ,shop_id: 5},
  { name: 'メロンパン', price: 220,category_id: 1,image:'メロンパン.jpg' ,shop_id: 5},
  { name: 'サンドイッチ', price: 300,category_id: 1,image:'サンドイッチ.jpg',shop_id: 5 },
  { name: 'あんぱん', price: 200,category_id: 1,image:'あんぱん.jpg',shop_id: 5 },
  { name: 'バゲット', price: 700,category_id: 1 ,image:'バゲット.jpg',shop_id: 5},
  { name: 'カレーパン', price: 300,category_id: 1 ,image:'カレーパン.jpg',shop_id: 6},
  { name: 'BLTサンド', price: 350,category_id: 1 ,image:'BLTサンド.jpeg',shop_id: 6},
  { name: 'たまごドッグ', price: 380,category_id: 1 ,image:'tajima1.jpg',shop_id: 7},
  { name: 'ナポリタンドッグ', price: 400,category_id: 1 ,image:'tajima2.jpg',shop_id: 7},
  { name: 'ハムチーズドッグ', price: 450,category_id: 1 ,image:'tajima3.jpg',shop_id: 7},
  { name: '厚切りとんかつドッグ', price: 500,category_id: 1 ,image:'tajima4.jpg',shop_id: 7},
  { name: '生食パン', price: 1000,category_id: 1 ,image:'生食パン.jpg',shop_id: 8}
  ])